services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    networks:
      - api-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "38MB"

  db:
    image: postgres:17-alpine
    hostname: rinha-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - api-network
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "120MB"

  api1: &api
    image: mpedroni/rinha-backend-2025:latest
    hostname: api1
    environment:
      - SERVICE_NAME=api-1
      - PORT=3000
      - DEBUG=true
      - DB_CONNECTION_STRING=postgres://postgres:postgres@db:5432/rinha?sslmode=disable
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - WORKERS_COUNT=4
    networks:
      - api-network
      - payment-processor
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "96MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - SERVICE_NAME=api-2
      - PORT=3000
      - DEBUG=true
      - DB_CONNECTION_STRING=postgres://postgres:postgres@db:5432/rinha?sslmode=disable
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - WORKERS_COUNT=4

networks:
  api-network:
    driver: bridge
  payment-processor:
    external: true
