services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    networks:
      - api-network
      - payment-processor

  db:
    image: postgres:17-alpine
    hostname: rinha-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - api-network

  api1: &api
    image: mpedroni/rinha-backend-2025:latest
    hostname: api1
    environment:
      - SERVICE_NAME=api-1
      - PORT=3000
      - DEBUG=true
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - api-network
      - payment-processor
    depends_on:
      - db

  api2:
    <<: *api
    hostname: api2
    environment:
      - SERVICE_NAME=api-2
      - PORT=3000
      - DEBUG=true
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    depends_on:
      - db

networks:
  api-network:
    driver: bridge
  payment-processor:
    external: true
